### PR TITLE
#11 flask setup

### PR DESCRIPTION
**Pull request by xiaoshi22**
Finished the Flask setup.

### CODE REVIEW

**Review by YufeiGao6 — APPROVED** [review]

**Comment by shivkhattar** [comment]
Could you run the test case to see if they work with nosetest?

**Comment by xiaoshi22** [comment]
> Could you run the test case to see if they work with nosetest?

Sure! I could run the test case once the nosetest branch is merged to Master.

**Comment by shivkhattar** [comment]
> > Could you run the test case to see if they work with nosetest?
> 
> Sure! I could run the test case once the nosetest branch is merged to Master.

@xiaoshi22 I just merged it. Could you take a pull?

**Comment by xiaoshi22** [comment]
> > > Could you run the test case to see if they work with nosetest?
> > 
> > 
> > Sure! I could run the test case once the nosetest branch is merged to Master.
> 
> @xiaoshi22 I just merged it. Could you take a pull?

I tested my code with Yufei's nosetest. It works!
```
venv) vagrant@orders:/vagrantnosetests -exe

REST API Server Tests 
- Test index call

Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
service/__init__.py       2      0   100%
service/service.py        7      1    86%   16
---------------------------------------------------
TOTAL                     9      1    89%
-----------------------------------------------------------------------------
1 test run in 0.192 seconds (1 test passed)
```

**Comment by shivkhattar** [comment]
> > > > Could you run the test case to see if they work with nosetest?
> > > 
> > > 
> > > Sure! I could run the test case once the nosetest branch is merged to Master.
> > 
> > 
> > @xiaoshi22 I just merged it. Could you take a pull?
> 
> I tested my code with Yufei's nosetest. It works!
> 
> ```
> venv) vagrant@orders:/vagrantnosetests -exe
> 
> REST API Server Tests 
> - Test index call
> 
> Name                  Stmts   Miss  Cover   Missing
> ---------------------------------------------------
> service/__init__.py       2      0   100%
> service/service.py        7      1    86%   16
> ---------------------------------------------------
> TOTAL                     9      1    89%
> -----------------------------------------------------------------------------
> 1 test run in 0.192 seconds (1 test passed)
> ```

@xiaoshi22 Let's try to keep the test coverage at 95%.

**Comment by xiaoshi22** [comment]
> > > > > Could you run the test case to see if they work with nosetest?
> > > > 
> > > > 
> > > > Sure! I could run the test case once the nosetest branch is merged to Master.
> > > 
> > > 
> > > @xiaoshi22 I just merged it. Could you take a pull?
> > 
> > 
> > I tested my code with Yufei's nosetest. It works!
> > ```
> > venv) vagrant@orders:/vagrantnosetests -exe
> > 
> > REST API Server Tests 
> > - Test index call
> > 
> > Name                  Stmts   Miss  Cover   Missing
> > ---------------------------------------------------
> > service/__init__.py       2      0   100%
> > service/service.py        7      1    86%   16
> > ---------------------------------------------------
> > TOTAL                     9      1    89%
> > -----------------------------------------------------------------------------
> > 1 test run in 0.192 seconds (1 test passed)
> > ```
> 
> @xiaoshi22 Let's try to keep the test coverage at 95%.

I feel that 89% is the best I can do. The missing line 16 in service.py indicated above is 
` app.run()` under main method, which I don't know how to write a test case for it. I think as we write more lines of code, we can cover up to 95%.

**Review by shivkhattar — APPROVED** [review]

**Pull request merged**
