### PR TITLE
Added skeleton feature file and steps folder for BDD testing

### PR DESCRIPTION
**Pull request by rutvik2151**

### CODE REVIEW

**Review by YufeiGao6 — CHANGES_REQUESTED** [review]
Could you add `Feature:` and `Background:` to `orders.feature`? So that when we write different Scenarios we won't be creating duplicate Feature and Background.

The Pets example:
```
Feature: The pet store service back-end
    As a Pet Store Owner
    I need a RESTful catalog service
    So that I can keep track of all my pets

Background:
    Given the following pets
        | name       | category | available |
        | fido       | dog      | True      |
        | kitty      | cat      | True      |
        | leo        | lion     | False     |
```

**Review by shivkhattar — APPROVED** [review]

**Review by jojodai — DISMISSED** [review]
looks great

**Review by YufeiGao6 — APPROVED** [review]

**Review by shivkhattar — APPROVED** [review]

**Comment by shivkhattar** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/d97e2552-e5d6-4314-93cd-4603445a8066?env_id=ibm:yp:us-south "orders-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/de2c1c4b-d454-4678-8c83-87825f7d8ab3 "order-pipeline") deployed [orders](https://github.com/NYU-Devops-2020-Orders-Team/orders/releases/tag/deploy-ibm-yp-us-south-sk8325-nyu.edu-dev-20201114-004445 "deploy-ibm-yp-us-south-sk8325-nyu.edu-dev-20201114-004445") to [dev](https://console.bluemix.net/apps/2df1ce90-4dbe-4be7-ae24-bb8fa0a1537e?env_id=ibm:yp:us-south "ibm:yp:us-south:sk8325@nyu.edu:dev"), including commit ba1df188550661e84021a52f18d4c736478c6dcf

**Comment by shivkhattar** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/d97e2552-e5d6-4314-93cd-4603445a8066?env_id=ibm:yp:us-south "orders-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/de2c1c4b-d454-4678-8c83-87825f7d8ab3 "order-pipeline") deployed [orders](https://github.com/NYU-Devops-2020-Orders-Team/orders/releases/tag/deploy-ibm-yp-us-south-sk8325-nyu.edu-prod-20201116-013849 "deploy-ibm-yp-us-south-sk8325-nyu.edu-prod-20201116-013849") to [prod](https://console.bluemix.net/apps/72e50e75-2807-435f-b5d1-e24358ccc3c9?env_id=ibm:yp:us-south "ibm:yp:us-south:sk8325@nyu.edu:prod"), including commit ba1df188550661e84021a52f18d4c736478c6dcf

**Pull request merged**
